language: php

php:
  - 7.2
  - 7.1
  - 7.0

install:
  - composer install --prefer-source

before_script:
  - composer self-update

script:
  - bin/phpunit -c phpunit.xml.dist --verbose $PHPUNIT_FLAGS